import tailwindcss from '@tailwindcss/vite'
import { ICON_COLLECTIONS, ICON_NAMES } from './icon/icon'

// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  compatibilityDate: '2025-07-15',

  // KunUI ships as a Nuxt layer (packages/ui). Extending it auto-imports
  // every <KunButton> / <KunChip> / ... component plus the layer's
  // app/composables, app/utils, shared/utils, and tailwindcss theme. moyu
  // no longer maintains a local kun copy — single source of truth in @kun/ui.
  extends: ['@kun/ui'],

  devtools: { enabled: false },

  modules: [
    '@nuxt/image',
    '@nuxt/icon',
    '@nuxt/eslint',
    '@nuxtjs/color-mode',
    '@pinia/nuxt',
    'pinia-plugin-persistedstate/nuxt',
    'nuxt-schema-org',
    'nuxt-umami'
  ],

  // Default provider stays IPX (galgame banners / user avatars need on-the-
  // -fly resize / re-encode). `none` is registered as a NAMED provider so
  // pre-optimized static assets (e.g. about post banners — already AVIF at
  // author time) can opt out per-image via `<NuxtImg provider="none">` and
  // skip the IPX → sharp roundtrip + filesystem cache miss latency.
  image: {
    providers: {
      none: { name: 'none', provider: '@nuxt/image/runtime/providers/none' }
    }
  },

  // Bundle only the icons we actually use. ICON_NAMES / ICON_COLLECTIONS are
  // generated by `npm run icons` from app/** — re-run after adding new icons.
  icon: {
    mode: 'svg',
    serverBundle: {
      collections: ICON_COLLECTIONS
    },
    clientBundle: {
      icons: ICON_NAMES,
      scan: false
    }
  },

  devServer: {
    host: '127.0.0.1',
    port: 6969
  },

  // Frontend
  css: ['~/styles/index.css'],

  imports: {
    dirs: ['shared/utils/**']
  },

  pinia: {
    storesDirs: ['./stores/**']
  },

  piniaPluginPersistedstate: {
    cookieOptions: {
      maxAge: 60 * 60 * 24 * 7,
      sameSite: 'strict'
    }
  },

  colorMode: {
    preference: 'system',
    fallback: 'light',
    globalName: '__KUNGALGAME_COLOR_MODE__',
    componentName: 'ColorScheme',
    classPrefix: 'kun-',
    classSuffix: '-mode',
    storageKey: 'kungalgame-color-mode'
  },

  vite: {
    plugins: [tailwindcss()]
  },

  umami: {
    id: process.env.KUN_VISUAL_NOVEL_FORUM_UMAMI_ID,
    host: 'https://stats.kungal.org/',
    autoTrack: true
  },

  runtimeConfig: {
    public: {
      // 本项目 Go Fiber API（不是 鲲 Galgame OAuth）。Go 端口从 apps/api/.env 的 KUN_SERVER_PORT 读，dev 默认 5214。
      apiBase:
        process.env.KUN_VISUAL_NOVEL_NUXT_PUBLIC_API_BASE ||
        'http://127.0.0.1:5214/api/v1',
      // 鲲 Galgame OAuth — 拆成两个 URL：
      // - oauthServerUrl：API base，给 fetch / 拿 token / 调 /users/batch 用（dev :9277）
      // - oauthWebUrl：用户面前端，给 window.location.href 跳转 /oauth/authorize / /register / /forgot / /profile 用（dev :9420）
      // prod 同域 `oauth.kungal.com`，但开发环境是两个端口，所以不能再从 API URL 推 origin。
      oauthServerUrl:
        process.env.NUXT_PUBLIC_KUN_OAUTH_SERVER_URL ||
        'http://127.0.0.1:9277/api/v1',
      oauthWebUrl:
        process.env.NUXT_PUBLIC_KUN_OAUTH_WEB_URL ||
        'http://127.0.0.1:9420',
      oauthClientId: process.env.NUXT_PUBLIC_KUN_OAUTH_CLIENT_ID || '',
      oauthRedirectUri: process.env.NUXT_PUBLIC_KUN_OAUTH_REDIRECT_URI || ''
    }
  }
})
