import { registerKunIcons } from '@kungal/ui-core'
import { KUN_APP_ICONS } from '~/utils/kunIcons.generated'

// Register moyu's app-level icons into @kungal/ui-core's icon registry so
// <KunIcon> (from @kungal/ui-vue) renders them as inline SVG — SSR and client
// emit identical markup with no @nuxt/icon network fetch and no hydration
// "double load". The set is generated by `npm run icons` (scripts/
// generate-icon-list.mjs). KunUI's own component icons are already bundled in
// @kungal/ui-core, so they're not duplicated here.
//
// Runs on both server and client (icons are needed in the SSR markup). The
// registry is a module-level singleton; re-registering the same static data
// each SSR request is idempotent.
export default defineNuxtPlugin(() => {
  registerKunIcons(KUN_APP_ICONS)
})
